### PR TITLE
Creates script to autogenerate HKObject support table

### PR DESCRIPTION
**Pull request by vishnuravi**
# Creates script to autogenerate HKObject support table

## :recycle: Current situation & Problem
Manually keeping a table of supported HealthKit types and associated codes/units updated is cumbersome.

## :bulb: Proposed solution
This PR adds a script that will generate a markdown table automatically from the mapping JSON file.

### Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordBDHG/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordBDHG/.github/blob/main/CONTRIBUTING.md):
- [X] I agree to follow the [Code of Conduct](https://github.com/StanfordBDHG/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordBDHG/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by PSchmiedmayer — CHANGES_REQUESTED** [review]
Thank you for the script creation @vishnuravi; that looks amazing!

I have two requests before we can merge the PR:
1. It would be great if we could move the script to a `Supporting` folder or something similar. `Scripts` might also be a good idea. The .md files should move to a `Documentation` folder to be aligned with the `Tests` and `Sources` structure we currently have in the repo.
2. I would suggest expanding to script to also generate the `HKCorrelationType` table as well. It might just be two rows, but that would still be a good step to automate everything we support and would set a positive prescience once we e.g., support `HKCategoryType`s in a future PR to then add this to the script and Documentation in the same PR.

**Comment by vishnuravi** [comment]
@PSchmiedmayer I have addressed your comments, please take another look when you have a chance. What do you think about Actions running this script and checking in the updated version?

**Comment by PSchmiedmayer** [comment]
@vishnuravi That looks great!

I like the idea of running the script in a GitHub action; that would be very cool. I would not suggest running this on every commit or PR, but rather use a manual trigger. Two things come to my mind:
1. Similar to our SPM version or ResearchKit, we could use a workflow trigger event to trigger the workflow on a feature branch, e.g., after you added some more types in a PR and it would push on that branch using the [`workflow_dispatch`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch) event.
2. Or use [`issue_comment`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment-on-issues-only-or-pull-requests-only) trigger that could be, e.g., triggered by commenting "Regenerate Documentation Table" or something like that.

I would slightly lean toward the first option but exploring the second one could also be nice 👍

**Review by PSchmiedmayer — APPROVED** [review]

**Comment by PSchmiedmayer** [comment]
@vishnuravi I have approved the PR but it would be great if you can include the small GitHub Action in this PR as well so we have it in place for the other PRs coming in like #23 🚀

**Pull request merged**
